# Day 16 - NumPy Array Operations
จุดประสงค์: ฝึกการคำนวณขั้นสูงกับ NumPy array

1. การดำเนินการทางคณิตศาสตร์

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)   # บวก
print(a - b)   # ลบ
print(a * b)   # คูณ
print(b / a)   # หาร
print(a ** 2)  # ยกกำลัง

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]


2. ฟังก์ชันทางคณิตศาสตร์ใน NumPy

In [2]:
data = np.array([1, 2, 3, 4, 5])

In [3]:
print(np.sqrt(data))   # รากที่สอง
print(np.exp(data))    # e^x
print(np.log(data))    # log ธรรมชาติ
print(np.sin(data))    # sine

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


3. การเปรียบเทียบและ Boolean Indexing

In [4]:
scores = np.array([85, 90, 78, 92, 88])

In [6]:
print(scores > 80)
print(scores[scores > 80])

[ True  True False  True  True]
[85 90 92 88]


4. การ Slicing

In [7]:
arr = np.array([10, 20, 30, 40, 50])

In [9]:
print(arr[1:4])   # index 1 ถึง 3
print(arr[:3])    # index 0 ถึง 2
print(arr[::2])   # ทุก 2 ก้าว

[20 30 40]
[10 20 30]
[10 30 50]


**5. การประยุกต์ใช้จริง**
- เลือกข้อมูลอุณหภูมิที่เกิน 33°C และคำนวณค่าเฉลี่ย

In [10]:
temps = np.array([32.5, 33.0, 31.8, 34.2, 35.0])

In [11]:
hot_days = temps[temps > 33]

In [12]:
print("วันที่ร้อน:", hot_days)
print("ค่าเฉลี่ยวันที่ร้อน =", np.mean(hot_days))

วันที่ร้อน: [34.2 35. ]
ค่าเฉลี่ยวันที่ร้อน = 34.6
